-- MySQL Script generated by MySQL Workbench
-- 01/17/17 14:19:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social_network` DEFAULT CHARACTER SET utf8 ;
USE `social_network` ;

-- -----------------------------------------------------
-- Table `social_network`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(128) NOT NULL,
  `pass` VARCHAR(128) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `e_mail` VARCHAR(128) NULL DEFAULT NULL,
  `website` VARCHAR(128) NULL DEFAULT NULL,
  `pic` VARCHAR(128) NULL,
  `create` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`article` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `create` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_usid_ar_usid_idx` (`user_id` ASC),
  CONSTRAINT `fk_usid_ar_usid`
    FOREIGN KEY (`user_id`)
    REFERENCES `social_network`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`article_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`article_comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_article` INT(11) NOT NULL,
  `text` MEDIUMTEXT NOT NULL,
  `create` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk-ar-com-usid_idx` (`id_user` ASC),
  INDEX `fk-ar-com-arid_idx` (`id_article` ASC),
  CONSTRAINT `fk-ar-com-arid`
    FOREIGN KEY (`id_article`)
    REFERENCES `social_network`.`article` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-ar-com-usid`
    FOREIGN KEY (`id_user`)
    REFERENCES `social_network`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`article_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`article_text` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_article` INT(11) NOT NULL,
  `text` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk-ar-te-usid_idx` (`id_user` ASC),
  INDEX `fk-ar-te-arid_idx` (`id_article` ASC),
  CONSTRAINT `fk-ar-te-arid`
    FOREIGN KEY (`id_article`)
    REFERENCES `social_network`.`article` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-ar-te-usid`
    FOREIGN KEY (`id_user`)
    REFERENCES `social_network`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`code` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_article` INT(11) NOT NULL,
  `text` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk-code-usid_idx` (`id_user` ASC),
  INDEX `fk-code-arid_idx` (`id_article` ASC),
  CONSTRAINT `fk-code-arid`
    FOREIGN KEY (`id_article`)
    REFERENCES `social_network`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-code-usid`
    FOREIGN KEY (`id_user`)
    REFERENCES `social_network`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`file` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_article` INT(11) NOT NULL,
  `id_user` INT(11) NOT NULL,
  `file` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk-fl-usid_idx` (`id_user` ASC),
  INDEX `fk-fl-arid_idx` (`id_article` ASC),
  CONSTRAINT `fk-fl-arid`
    FOREIGN KEY (`id_article`)
    REFERENCES `social_network`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-fl-usid`
    FOREIGN KEY (`id_user`)
    REFERENCES `social_network`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`interest` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`user_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`user_interest` (
  `id_user` INT(11) NOT NULL,
  `id_interest` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`, `id_interest`),
  INDEX `fk_us_int_intid_idx` (`id_interest` ASC),
  CONSTRAINT `fk_us_int_intid`
    FOREIGN KEY (`id_interest`)
    REFERENCES `social_network`.`interest` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_us_int_usid`
    FOREIGN KEY (`id_user`)
    REFERENCES `social_network`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `to_id_user` INT NOT NULL,
  `text` MEDIUMTEXT NOT NULL,
  `read` TINYINT(1) NOT NULL DEFAULT 0,
  `create` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk-mes-usid_idx` (`id_user` ASC),
  INDEX `f-mes-tousid_idx` (`to_id_user` ASC),
  CONSTRAINT `fk-mes-usid`
    FOREIGN KEY (`id_user`)
    REFERENCES `social_network`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `f-mes-tousid`
    FOREIGN KEY (`to_id_user`)
    REFERENCES `social_network`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`user_friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`user_friend` (
  `id_user` INT NOT NULL,
  `id_friend` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_friend`),
  INDEX `fk-us-fr-frid_idx` (`id_friend` ASC),
  CONSTRAINT `fk_us-fr-usid`
    FOREIGN KEY (`id_user`)
    REFERENCES `social_network`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-us-fr-frid`
    FOREIGN KEY (`id_friend`)
    REFERENCES `social_network`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
